#!/usr/bin/env python

import podcastparser
import urllib
import socket, sys, ConfigParser

feedurl = "http://crankygamersuk.libsyn.com/rss"

if len(sys.argv) > 1:
	feedurl = sys.argv[1]

parsed = podcastparser.parse(feedurl, urllib.urlopen(feedurl))

episode = parsed['episodes'][0]['enclosures'][0]['url']

config = ConfigParser.ConfigParser()
config.read(['../dot3k.cfg','dot3k.cfg'])

host = '127.0.0.1'
port = 9393

print('Playing: ' + episode)
try:
	sck = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sck.connect((host, port))
	sck.send('clear\n')
	sck.send('add ' + episode + '\n')
	sck.send('play\n')
except socket.error:
	exit('Unable to connect to server: ' + host + ':' + str(port))
