#!/usr/bin/env python

import socket
import sys
import urllib

try:
    import ConfigParser
except ImportError:
    import configparser as ConfigParser

try:
    import podcastparser
except ImportError:
    sys.exit("This script requires the podcastparser module\nInstall with: sudo pip install podcastparser")


feedurl = "http://crankygamersuk.libsyn.com/rss"
episode_idx = 0

if len(sys.argv) > 1:
    feedurl = sys.argv[1]

if len(sys.argv) > 2:
    episode_idx = int(sys.argv[2])

parsed = podcastparser.parse(feedurl, urllib.urlopen(feedurl))

episode = parsed['episodes'][episode_idx]['enclosures'][0]['url']

config = ConfigParser.ConfigParser()
config.read(['../dot3k.cfg', 'dot3k.cfg'])

host = '127.0.0.1'
port = 9393

print('Playing: ' + episode)
try:
    sck = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sck.connect((host, port))
    sck.send('clear\n')
    sck.send('add ' + episode + '\n')
    sck.send('play\n')
except socket.error:
    exit('Unable to connect to server: ' + host + ':' + str(port))
